version: "3"
services:
    # Laravel application
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9090:9090"
        volumes:
            - .:/var/www/html
        networks:
            - laravel-net
    # Nginx
    webserver:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-net
    # MongoDB
    mongo:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        networks:
            - laravel-net
    # Mongo Express
    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - "8081:8081"  # Change to "8081:8081" to use port 8081 on the host
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
        networks:
            - laravel-net
    # Redis
    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        networks:
            - laravel-net
networks:
    laravel-net:
        driver: bridge
